"""add programme manager

Revision ID: 02409ae15405
Revises: 2bc29cc7d1b0
Create Date: 2021-06-02 22:17:20.288285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "02409ae15405"
down_revision = "2bc29cc7d1b0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("programme", sa.Column("manager_id", postgresql.UUID(), nullable=True))
    op.drop_index("ix_programme_programme_manager", table_name="programme")
    op.create_index(op.f("ix_programme_manager_id"), "programme", ["manager_id"], unique=False)
    op.create_foreign_key(None, "programme", "person", ["manager_id"], ["id"], ondelete="SET NULL")
    op.drop_column("programme", "programme_manager")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "programme",
        sa.Column("programme_manager", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "programme", type_="foreignkey")
    op.drop_index(op.f("ix_programme_manager_id"), table_name="programme")
    op.create_index(
        "ix_programme_programme_manager",
        "programme",
        ["programme_manager"],
        unique=False,
    )
    op.drop_column("programme", "manager_id")
    # ### end Alembic commands ###
