"""add practice head relationship

Revision ID: 2bc29cc7d1b0
Revises: c6a8aa369830
Create Date: 2021-05-30 11:43:50.420703

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2bc29cc7d1b0"
down_revision = "c6a8aa369830"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("practice", sa.Column("head_id", postgresql.UUID(), nullable=True))
    op.drop_index("ix_practice_head", table_name="practice")
    op.create_index(op.f("ix_practice_head_id"), "practice", ["head_id"], unique=False)
    op.create_foreign_key(None, "practice", "person", ["head_id"], ["id"], ondelete="SET NULL")
    op.drop_column("practice", "head")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("practice", sa.Column("head", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "practice", type_="foreignkey")
    op.drop_index(op.f("ix_practice_head_id"), table_name="practice")
    op.create_index("ix_practice_head", "practice", ["head"], unique=False)
    op.drop_column("practice", "head_id")
    # ### end Alembic commands ###
