"""add cost centre to practice

Revision ID: 6bc5a69c1efc
Revises: 782a63915495
Create Date: 2021-06-28 13:42:04.064844

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6bc5a69c1efc"
down_revision = "782a63915495"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("practice", sa.Column("cost_centre", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("practice", "cost_centre")
    # ### end Alembic commands ###
