"""add grade

Revision ID: 73ffdedf5a21
Revises: feff0a935860
Create Date: 2021-05-12 20:44:42.488521

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "73ffdedf5a21"
down_revision = "feff0a935860"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grade",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("organisation_id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_grade_created_at"), "grade", ["created_at"], unique=False)
    op.create_index(op.f("ix_grade_name"), "grade", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_grade_name"), table_name="grade")
    op.drop_index(op.f("ix_grade_created_at"), table_name="grade")
    op.drop_table("grade")
    # ### end Alembic commands ###
