"""empty message

Revision ID: ae7cac779f95
Revises: 02409ae15405
Create Date: 2021-06-05 00:06:25.521434

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae7cac779f95"
down_revision = "02409ae15405"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "practice_id", existing_type=postgresql.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("role", "practice_id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###
