"""initial migration

Revision ID: b8e5393af39d
Revises:
Create Date: 2021-05-09 23:48:21.949013

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b8e5393af39d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisation",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_organisation_created_at"), "organisation", ["created_at"], unique=False)
    op.create_index(op.f("ix_organisation_domain"), "organisation", ["domain"], unique=True)
    op.create_index(op.f("ix_organisation_name"), "organisation", ["name"], unique=False)
    op.create_table(
        "programme",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("organisation_id", postgresql.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organisation_id"], ["organisation.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_programme_created_at"), "programme", ["created_at"], unique=False)
    op.create_index(op.f("ix_programme_name"), "programme", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_programme_name"), table_name="programme")
    op.drop_index(op.f("ix_programme_created_at"), table_name="programme")
    op.drop_table("programme")
    op.drop_index(op.f("ix_organisation_name"), table_name="organisation")
    op.drop_index(op.f("ix_organisation_domain"), table_name="organisation")
    op.drop_index(op.f("ix_organisation_created_at"), table_name="organisation")
    op.drop_table("organisation")
    # ### end Alembic commands ###
