"""add status to project

Revision ID: bf6b10f0f3e8
Revises: 2ad39b3ab779
Create Date: 2021-06-15 13:21:24.484156

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bf6b10f0f3e8"
down_revision = "2ad39b3ab779"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("status", sa.String(), nullable=False))
    op.create_index(op.f("ix_project_status"), "project", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_project_status"), table_name="project")
    op.drop_column("project", "status")
    # ### end Alembic commands ###
