"""add employment

Revision ID: c6a8aa369830
Revises: 9506165d022f
Create Date: 2021-05-24 22:44:14.757603

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c6a8aa369830"
down_revision = "9506165d022f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("person", sa.Column("employment", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "employment")
    # ### end Alembic commands ###
